### ISSUE TITLE
使用Github搭建自己的个人博客 — Feedliu

### ISSUE THREAD

**Issue by feedliu** [feedliu/blog-comments#9]
https://feedliu.github.io/2019/02/15/build-your-own-blog-site/ 

 现在，越来越多的技术人员都有写博客的习惯，来记录学习笔记、分享个人想法、与同行交流等等。这导致了大量博客、社交网站的兴起，比如csdn、简书、博客园、知乎等等。但是这些都是借助别人的平台，有诸多不便，比如你的博客样式是平台定的，你的博客可能有大量的广告，等等。如果你想拥有个性化的、纯净的博客，你可以自己搭建一个博客平台，可能需要一下这些步骤：  购买域名  部署网站  设计网站样式

**Comment by luis-ai-systems** [comment]
Thank you！
